name: Credit Card Processing
favicon: null
layout_spectrum: 0.27625533868558705
typography_spectrum: 0.017607325688004494
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5609407955780625
  lightness: 0.8485480225645006
  saturation: 0.5508327027782798
  rhythmicContrast: 0.4988412626553327
purpose: []
